STARTCOMMENT

STARTVERSION
1.0
# 1. A charactor line should no longer than 250 ASCI chars
# 2. When a line longer that 250 chars, return the line
#    and paded with "\n"
# 3. "\n" must followed with return
# 4. this is SFC version
ENDVERSION

ENDCOMMENT

STARTENGLISH

#MSG_MAIN_MENU_0
Video/Audio

#MSG_MAIN_MENU_1
Save State

#MSG_MAIN_MENU_2
Cheats

#MSG_MAIN_MENU_3
Tools

#MSG_MAIN_MENU_4
Other

#MSG_MAIN_MENU_5
Exit

#MSG_SUB_MENU_00
Graphic                %s

#MSG_SUB_MENU_01
Game Fast Forward     %s

#MSG_SUB_MENU_02
Frame Skip Level         %s

#MSG_SUB_MENU_03
Frame Skip Level         %d

#MSG_SUB_MENU_04
Sound Enable             %s

#MSG_SUB_MENU_05
Back

#MSG_SUB_MENU_10
Write Game State

#MSG_SUB_MENU_11
Read Game State    %d

#MSG_SUB_MENU_12
Game State Slot

#MSG_SUB_MENU_13
Delete Game State

#MSG_SUB_MENU_14
Back

#MSG_SUB_MENU_20
Cheat Page: %d

#MSG_SUB_MENU_21
Load Cheat File

#MSG_SUB_MENU_22
Cheat Slot

#MSG_SUB_MENU_23
Load Cheats

#MSG_SUB_MENU_24
Back

#MSG_SUB_MENU_30
Screen Snapshot

#MSG_SUB_MENU_31
Key Pad Remap

#MSG_SUB_MENU_32
Period                     %s Second

#MSG_SUB_MENU_40
Auto Standby          %s

#MSG_SUB_MENU_41
Language               %s

#MSG_SUB_MENU_42
CPU Frequence          %d

#MGS_SUB_MENU_43
SD Card Capacity

#MSG_SUB_MENU_44
Restore Default Settings

#MSG_SUB_MENU_45
Version Information

#MSG_SUB_MENU_300
Save Screen Snapshot

#MSG_SUB_MENU_301
Browse Screen Snapshots

#MSG_SUB_MENU_302
Time Backward        %s

#MSG_SUB_MENU_310
SNES Key    A                %s

#MSG_SUB_MENU_311
                 B                %s

#MSG_SUB_MENU_312
                 Rapid A      %s

#MSG_SUB_MENU_313
                 Rapid B      %s

#MSG_SUB_MENU_314
Awaken Menu            %s

#MSG_SUB_MENU_315
Back                           NDS key

#MSG_SUB_MENU_60
Recently Played Games

#MSG_SUB_MENU_61
Select Games

#MSG_SUB_MENU_62
Loading Game

#MSG_SCREEN_RATIO_0
Display Mode 0

#MSG_SCREEN_RATIO_1
Display Mode 1

#MSG_SCREEN_RATIO_2,
Display Mode 2

#MSG_SCREEN_RATIO_3,
Display Mode 3

#MSG_SCREEN_RATIO_4,
Display Mode 4

#MSG_FRAMESKIP_0
Manual

#MSG_FRAMESKIP_1
Automatic

#MSG_ON_OFF_0
Off

#MSG_ON_OFF_1
On

#MSG_SOUND_SWITCH_0
On

#MSG_SOUND_SWITCH_1
Mute

#MSG_SNAP_FRAME_0
Current Frames

#MSG_SNAP_FRAME_1
Last Frame

#MSG_EN_DIS_ABLE_0
Disable

#MSG_EN_DIS_ABLE_1
Enable

#MSG_NONE_LOAD_GAME
No Game Loaded!

#MSG_CHEAT_MENU_NON_LOAD
Cheat %d (None Loaded)

#MSG_CHEAT_MENU_0
Cheat %d (%s): %%s

#MSG_LOAD_STATE
Load Savestate

#MSG_LOAD_STATE_END
Load Savestate

#MSG_SAVE_STATE
Save Savestate

#MSG_SAVE_STATE_END
Successful!

#MSG_KEY_MAP_NONE
None

#MSG_KEY_MAP_A
A

#MSG_KEY_MAP_B
B

#MSG_KEY_MAP_SL
SELECT

#MSG_KEY_MAP_ST
START

#MSG_KEY_MAP_RT
→

#MSG_KEY_MAP_LF
←

#MSG_KEY_MAP_UP
↑

#MSG_KEY_MAP_DW
↓

#MSG_HOME_MAP_R
R

#MSG_HOME_MAP_L
L

#MSG_HOME_MAP_X
X

#MSG_HOME_MAP_Y
Y

#MSG_HOME_MAP_TOUCH
Touch Screen

#MSG_SAVESTATE_EMPTY
Current Slot Is Empty!

#MSG_SAVESTATE_FULL
Current Slot Is Full,\n
Do You Want To Overwrite It?\n
Press A To Overwrite\n
Press B To Cancel

#MSG_SAVESTATE_DOING
Writing...

#MSG_SAVESTATE_FAILURE
Failure!\n
Press A To Retry\n
Press B To Cancel

#MSG_SAVESTATE_SUCCESS
Success!

#MSG_SAVESTATE_SLOT_EMPTY
No Screen Shot

#MSG_SAVESTATE_FILE_BAD
Game State Could Not Be Found Or Is Corrupt!

#MSG_LOADSTATE_DOING
Loading...

#MSG_LOADSTATE_FAILURE
Failure!

#MSG_LOADSTATE_SUCCESS
Success!

#MSG_WARING_DIALOG
Press Any Key To Return

#MSG_TIME_FORMATE
Time

#MSG_SUB_MENU_130
Delete All Game States?

#MSG_SUB_MENU_131
Delete Game State         %d ?

#MSG_DELETE_ALL_SAVESTATE_WARING
Delete All Game States? \n
Press A To Confirm, Press B To Cancel

#MSG_DELETE_SINGLE_SAVESTATE_WARING
Delete Game State %d? \n
Press A To Confirm, Press B To Cancel

#MSG_DELETE_SAVESTATE_NOTHING
There Is Nothing To Delete!

#MSG_SAVE_SNAPSHOT
Saving Screen Snapshot...

#MSG_SAVE_SNAPSHOT_COMPLETE
Complete!

#MSG_SAVE_SNAPSHOT_FAILURE
Failure!

#MSG_CHANGE_LANGUAGE
Changing...

#MSG_CHANGE_LANGUAGE_WAITING
Please Wait...

#MSG_NO_SLIDE
No Screenshot Found!

#MSG_PLAYING_SLIDE
Playing...

#MSG_PAUSE_SLIDE
Pause...

#MSG_PLAY_SLIDE1
Key UP    Speed up

#MSG_PLAY_SLIDE2
Key DOWN  Speed down

#MSG_PLAY_SLIDE3
Key LEFT  Last slide

#MSG_PLAY_SLIDE4
Key RIGHT Next slide

#MSG_PLAY_SLIDE5
Key A     Pause

#MSG_PLAY_SLIDE6
Key B     Return To Menu

#MSG_LOADING_GMAE
Loading Game...

#MSG_EMU_VERSION0
SNES Emulator

#MSG_EMU_VERSION1
Version

#MSG_LOAD_DEFAULT_WARING,
Reset SNES Emulator To Default Settings?

#MSG_DEFAULT_LOADING
Please Wait A Moment...

#MSG_BACK
Back

ENDENGLISH



STARTCHINESESIM

#MSG_MAIN_MENU_0
图像声音

#MSG_MAIN_MENU_1
存档

#MSG_MAIN_MENU_2
作弊器

#MSG_MAIN_MENU_3
工具

#MSG_MAIN_MENU_4
综合设置

#MSG_MAIN_MENU_5
退出模拟器

#MSG_SUB_MENU_00
画面                 %s

#MSG_SUB_MENU_01
游戏快进                 %s

#MSG_SUB_MENU_02
跳帧方式                 %s

#MSG_SUB_MENU_03
跳帧级别                 %d

#MSG_SUB_MENU_04
声音开关                 %s

#MSG_SUB_MENU_05
返回

#MSG_SUB_MENU_10
写入存档

#MSG_SUB_MENU_11
读取存档                   %d

#MSG_SUB_MENU_12
存档槽选择

#MSG_SUB_MENU_13
删除存档

#MSG_SUB_MENU_14
返回

#MSG_SUB_MENU_20
作弊代码页   %d

#MSG_SUB_MENU_21
加载作弊代码文件

#MSG_SUB_MENU_22
作弊代码

#MSG_SUB_MENU_23
加载作弊文件

#MSG_SUB_MENU_24
返回

#MSG_SUB_MENU_30
屏幕快照

#MSG_SUB_MENU_31
按键重映射

#MSG_SUB_MENU_32
时间长度                   %s 秒

#MSG_SUB_MENU_40
自动待机                  %s

#MSG_SUB_MENU_41
语言                       %s

#MSG_SUB_MENU_42
CPU主频                  %d

#MGS_SUB_MENU_43
SD卡容量

#MSG_SUB_MENU_44
缺省设置

#MSG_SUB_MENU_45
版本信息

#MSG_SUB_MENU_300
保存屏幕快照

#MSG_SUB_MENU_301
浏览屏幕快照

#MSG_SUB_MENU_302
时之沙                       %s

#MSG_SUB_MENU_310
SFC 按键    A               %s

#MSG_SUB_MENU_311
                 B               %s

#MSG_SUB_MENU_312
                 连发  A       %s

#MSG_SUB_MENU_313
                 连发  B       %s

#MSG_SUB_MENU_314
唤醒菜单键                   %s

#MSG_SUB_MENU_315
返回                           NDS 按键

#MSG_SUB_MENU_60
最近玩过的游戏

#MSG_SUB_MENU_61
新游戏

#MSG_SUB_MENU_62
装载游戏

#MSG_SCREEN_RATIO_0
显示模式 0

#MSG_SCREEN_RATIO_1
显示模式 1

#MSG_SCREEN_RATIO_2,
显示模式 2

#MSG_SCREEN_RATIO_3,
显示模式 3

#MSG_FRAMESKIP_0
手动

#MSG_FRAMESKIP_1
自动

#MSG_ON_OFF_0
关

#MSG_ON_OFF_1
开

#MSG_SOUND_SWITCH_0
开

#MSG_SOUND_SWITCH_1
静音

#MSG_SNAP_FRAME_0
当前帧

#MSG_SNAP_FRAME_1
前一帧

#MSG_EN_DIS_ABLE_0
禁止

#MSG_EN_DIS_ABLE_1
允许

#MSG_NONE_LOAD_GAME
没有加载游戏

#MSG_CHEAT_MENU_NON_LOAD
作弊代码  %d  (没有加载)

#MSG_CHEAT_MENU_LOADED
作弊代码  %d  (%s): %%s

#MSG_LOAD_STATE
装载即时存档

#MSG_LOAD_STATE_END
装载即时存档完成

#MSG_SAVE_STATE
保存即时存档

#MSG_SAVE_STATE_END
保存即时存档完成

#MSG_KEY_MAP_NONE
无

#MSG_KEY_MAP_A
A

#MSG_KEY_MAP_B
B

#MSG_KEY_MAP_SL
SELECT

#MSG_KEY_MAP_ST
START

#MSG_KEY_MAP_RT
→

#MSG_KEY_MAP_LF
←

#MSG_KEY_MAP_UP
↑

#MSG_KEY_MAP_DW
↓

#MSG_HOME_MAP_R
R

#MSG_HOME_MAP_L
L

#MSG_HOME_MAP_X
X

#MSG_HOME_MAP_Y
Y

#MSG_HOME_MAP_TOUCH
触摸屏

#MSG_SAVESTATE_EMPTY
当前存档槽没有存档文件!

#MSG_SAVESTATE_EMPTY
当前存档槽已有存档文件,\n
覆盖已有存档吗?\n
按 A 键覆盖\n
按 B 键取消


#MSG_SAVESTATE_DOING
正在写入...

#MSG_SAVESTATE_FAILURE
写入存档失败!\n
按 A 键重试\n
按 B 键取消

#MSG_SAVESTATE_SUCCESS
写入存档成功!

#MSG_SAVESTATE_SLOT_EMPTY
没有游戏截图

#MSG_SAVESTATE_FILE_BAD
存档文件找不到或者损坏!

#MSG_LOADSTATE_DOING
正在加载...

#MSG_LOADSTATE_FAILURE
加载存档失败

#MSG_LOADSTATE_SUCCESS
加载存档成功

#MSG_WARING_DIALOG
按任意键返回

#MSG_TIME_FORMATE
时间

#MSG_SUB_MENU_130
删除当前游戏的所有存档

#MSG_SUB_MENU_131
删除当前游戏的一个存档         %d

#MSG_DELETE_ALL_SAVESTATE_WARING
确定要删除所有存档吗？\n
按 A 键确定 \n
按 B 键取消

#MSG_DELETE_SINGLE_SAVESTATE_WARING
确定要删除存档槽 %d 的存档吗? \n
按 A 键确定 \n
按 B 键取消

#MSG_DELETE_SAVESTATE_NOTHING
没有存档可删除

#MSG_SAVE_SNAPSHOT
正在保存屏幕快照...

#MSG_SAVE_SNAPSHOT_CONPLETE
完成!

#MSG_SAVE_SNAPSHOT_FAILURE
失败!

#MSG_CHANGE_LANGUAGE
正在修改...

#MSG_CHANGE_LANGUAGE_WAITING
请稍候!

#MSG_NO_SLIDE
此目录没有屏幕快照，取消放映

#MSG_PLAYING_SLIDE
正在播放

#MSG_PAUSE_SLIDE
已暂停

#MSG_PLAY_SLIDE1
按键 上  加快播放

#MSG_PLAY_SLIDE2
按键 下  减慢播放

#MSG_PLAY_SLIDE3
按键 左  上一帧

#MSG_PLAY_SLIDE4
按键 右  下一帧

#MSG_PLAY_SLIDE5
按键 A   暂停

#MSG_PLAY_SLIDE6
按键 B   返回菜单

#MSG_LOADING_GMAE
正在装载游戏...

#MSG_EMU_VERSION0
SFC模拟器

#MSG_EMU_VERSION1
版本

#MSG_LOAD_DEFAULT_WARING,
确定将 SFC模拟器恢复为出厂设置吗?

#MSG_DEFAULT_LOADING
正在设置,请稍候...

#MSG_BACK
返回

ENDCHINESESIM