STARTCOMMENT

STARTVERSION
1.0
# 1. A charactor line should no longer than 250 ASCI chars
# 2. When a line longer that 250 chars, return the line
#    and paded with "\n"
# 3. "\n" must followed with return
# 4. this is SFC version
ENDVERSION

ENDCOMMENT

STARTENGLISH

#MSG_MAIN_MENU_0
Video & audio

#MSG_MAIN_MENU_1
Saved states

#MSG_MAIN_MENU_2
Cheats

#MSG_MAIN_MENU_3
Tools

#MSG_MAIN_MENU_4
Options

#MSG_MAIN_MENU_5
Exit

#MSG_SUB_MENU_00
Aspect ratio    %s

#MSG_SUB_MENU_01
Fast-forward  %s

#MSG_SUB_MENU_02
Frame skipping        %s

#MSG_SUB_MENU_03
Frame skipping        %d

#MSG_SUB_MENU_04
Sound              %s

#MSG_SUB_MENU_05
Back

#MSG_SUB_MENU_10
Create saved state

#MSG_SUB_MENU_11
Load saved state          %d

#MSG_SUB_MENU_12
Select save slot

#MSG_SUB_MENU_13
Delete saved states...

#MSG_SUB_MENU_14
Back

#MSG_SUB_MENU_20
Cheat page %d

#MSG_SUB_MENU_21
Load cheat file

#MSG_SUB_MENU_22
Cheat slot

#MSG_SUB_MENU_23
Load cheats

#MSG_SUB_MENU_24
Back

#MSG_SUB_MENU_30
Screenshots...

#MSG_SUB_MENU_31
Remap the joypad

#MSG_SUB_MENU_32
Keep information for  %s second(s)

#MSG_SUB_MENU_40
Auto standby          %s

#MSG_SUB_MENU_41
Language                          %s

#MSG_SUB_MENU_42
CPU frequency                 %d

#MGS_SUB_MENU_43
Card capacity

#MSG_SUB_MENU_44
Restore default settings

#MSG_SUB_MENU_45
Version information

#MSG_SUB_MENU_300
Save a screenshot

#MSG_SUB_MENU_301
Browse screenshots

#MSG_SUB_MENU_302
Rewinding             %s

#MSG_SUB_MENU_310
SNES Key    A                %s

#MSG_SUB_MENU_311
                 B                %s

#MSG_SUB_MENU_312
                 Rapid A      %s

#MSG_SUB_MENU_313
                 Rapid B      %s

#MSG_SUB_MENU_314
Awaken Menu            %s

#MSG_SUB_MENU_315
Back                           NDS key

#MSG_SUB_MENU_60
Recently played games

#MSG_SUB_MENU_61
Select a game from the card

#MSG_SUB_MENU_62
Select a game

#MSG_SCREEN_RATIO_0
[0] Resized, entire screen

#MSG_SCREEN_RATIO_1
[1] Original, show the bottom

#MSG_SCREEN_RATIO_2,
[2] Original, show the top

#MSG_SCREEN_RATIO_3,
[3] Original, show the middle

#MSG_SCREEN_RATIO_4,
[4] Resized, entire screen

#MSG_FRAMESKIP_0
Manual

#MSG_FRAMESKIP_1
Automatic

#MSG_ON_OFF_0
Off

#MSG_ON_OFF_1
On

#MSG_SOUND_SWITCH_0
On

#MSG_SOUND_SWITCH_1
Mute

#MSG_SNAP_FRAME_0
Current Frames

#MSG_SNAP_FRAME_1
Last Frame

#MSG_EN_DIS_ABLE_0
Disable

#MSG_EN_DIS_ABLE_1
Enable

#MSG_NONE_LOAD_GAME
No game is currently loaded

#MSG_CHEAT_MENU_NON_LOAD
Cheat %d (none loaded)

#MSG_CHEAT_MENU_0
Cheat %d (%s): %%s

#MSG_LOAD_STATE
Load saved state

#MSG_LOAD_STATE_END
Load saved state

#MSG_SAVE_STATE
Create a saved state

#MSG_SAVE_STATE_END
OK!

#MSG_KEY_MAP_NONE
None

#MSG_KEY_MAP_A
A

#MSG_KEY_MAP_B
B

#MSG_KEY_MAP_SL
SELECT

#MSG_KEY_MAP_ST
START

#MSG_KEY_MAP_RT
→

#MSG_KEY_MAP_LF
←

#MSG_KEY_MAP_UP
↑

#MSG_KEY_MAP_DW
↓

#MSG_HOME_MAP_R
R

#MSG_HOME_MAP_L
L

#MSG_HOME_MAP_X
X

#MSG_HOME_MAP_Y
Y

#MSG_HOME_MAP_TOUCH
Touch Screen

#MSG_SAVESTATE_EMPTY
This slot is empty.

#MSG_SAVESTATE_FULL
The current slot holds a state.\n
Do you wish to overwrite it?\n
[A] Overwrite  [B] Cancel

#MSG_SAVESTATE_DOING
Saving state...

#MSG_SAVESTATE_FAILURE
Failed!\n
[A] Retry  [B] Cancel

#MSG_SAVESTATE_SUCCESS
OK!

#MSG_SAVESTATE_SLOT_EMPTY
No saved state

#MSG_SAVESTATE_FILE_BAD
The game state file is not found or is corrupt.

#MSG_LOADSTATE_DOING
Loading...

#MSG_LOADSTATE_FAILURE
Failed!

#MSG_LOADSTATE_SUCCESS
OK!

#MSG_WARING_DIALOG
Press any key to return.

#MSG_TIME_FORMATE
Time

#MSG_SUB_MENU_130
Delete all saved states

#MSG_SUB_MENU_131
Delete saved state %d

#MSG_DELETE_ALL_SAVESTATE_WARING
Really delete all saved states?\n
[A] Confirm  [B] Cancel

#MSG_DELETE_SINGLE_SAVESTATE_WARING
Really delete saved state %d?\n
[A] Confirm  [B] Cancel

#MSG_DELETE_SAVESTATE_NOTHING
There's already nothing here.

#MSG_SAVE_SNAPSHOT
Saving a screenshot...

#MSG_SAVE_SNAPSHOT_COMPLETE
OK!

#MSG_SAVE_SNAPSHOT_FAILURE
Failed!

#MSG_CHANGE_LANGUAGE
Changing language...

#MSG_CHANGE_LANGUAGE_WAITING
Please wait...

#MSG_NO_SLIDE
No screenshots found

#MSG_PLAYING_SLIDE
Playing...

#MSG_PAUSE_SLIDE
Pause...

#MSG_PLAY_SLIDE1
Key UP    Speed up

#MSG_PLAY_SLIDE2
Key DOWN  Slow down

#MSG_PLAY_SLIDE3
Key LEFT  Last image

#MSG_PLAY_SLIDE4
Key RIGHT Next image

#MSG_PLAY_SLIDE5
Key A     Pause

#MSG_PLAY_SLIDE6
Key B     Return to the menu

#MSG_LOADING_GMAE
Loading...

#MSG_EMU_VERSION0
CATSFC SNES emulator

#MSG_EMU_VERSION1
Version

#MSG_LOAD_DEFAULT_WARING,
Reset all settings to defaults?

#MSG_DEFAULT_LOADING
Please wait...

#MSG_BACK
Back

ENDENGLISH



STARTCHINESESIM

#MSG_MAIN_MENU_0
图像声音

#MSG_MAIN_MENU_1
存档

#MSG_MAIN_MENU_2
作弊器

#MSG_MAIN_MENU_3
工具

#MSG_MAIN_MENU_4
综合设置

#MSG_MAIN_MENU_5
退出模拟器

#MSG_SUB_MENU_00
画面                       %s

#MSG_SUB_MENU_01
游戏快进                 %s

#MSG_SUB_MENU_02
跳帧方式                 %s

#MSG_SUB_MENU_03
跳帧级别                 %d

#MSG_SUB_MENU_04
声音开关                 %s

#MSG_SUB_MENU_05
返回

#MSG_SUB_MENU_10
写入存档

#MSG_SUB_MENU_11
读取存档                        %d

#MSG_SUB_MENU_12
存档槽选择

#MSG_SUB_MENU_13
删除存档

#MSG_SUB_MENU_14
返回

#MSG_SUB_MENU_20
作弊代码页   %d

#MSG_SUB_MENU_21
加载作弊代码文件

#MSG_SUB_MENU_22
作弊代码

#MSG_SUB_MENU_23
加载作弊文件

#MSG_SUB_MENU_24
返回

#MSG_SUB_MENU_30
屏幕快照

#MSG_SUB_MENU_31
按键重映射

#MSG_SUB_MENU_32
时间长度                   %s 秒

#MSG_SUB_MENU_40
自动待机                  %s

#MSG_SUB_MENU_41
语言                               %s

#MSG_SUB_MENU_42
CPU主频                          %d

#MGS_SUB_MENU_43
卡容量

#MSG_SUB_MENU_44
缺省设置

#MSG_SUB_MENU_45
版本信息

#MSG_SUB_MENU_300
保存屏幕快照

#MSG_SUB_MENU_301
浏览屏幕快照

#MSG_SUB_MENU_302
时之沙                       %s

#MSG_SUB_MENU_310
SFC 按键    A               %s

#MSG_SUB_MENU_311
                 B               %s

#MSG_SUB_MENU_312
                 连发  A       %s

#MSG_SUB_MENU_313
                 连发  B       %s

#MSG_SUB_MENU_314
唤醒菜单键                   %s

#MSG_SUB_MENU_315
返回                           NDS 按键

#MSG_SUB_MENU_60
最近玩过的游戏

#MSG_SUB_MENU_61
新游戏

#MSG_SUB_MENU_62
装载游戏

#MSG_SCREEN_RATIO_0
显示模式 0

#MSG_SCREEN_RATIO_1
显示模式 1

#MSG_SCREEN_RATIO_2,
显示模式 2

#MSG_SCREEN_RATIO_3,
显示模式 3

#MSG_FRAMESKIP_0
手动

#MSG_FRAMESKIP_1
自动

#MSG_ON_OFF_0
关

#MSG_ON_OFF_1
开

#MSG_SOUND_SWITCH_0
开

#MSG_SOUND_SWITCH_1
静音

#MSG_SNAP_FRAME_0
当前帧

#MSG_SNAP_FRAME_1
前一帧

#MSG_EN_DIS_ABLE_0
禁止

#MSG_EN_DIS_ABLE_1
允许

#MSG_NONE_LOAD_GAME
没有加载游戏

#MSG_CHEAT_MENU_NON_LOAD
作弊代码  %d  (没有加载)

#MSG_CHEAT_MENU_LOADED
作弊代码  %d  (%s): %%s

#MSG_LOAD_STATE
装载即时存档

#MSG_LOAD_STATE_END
装载即时存档完成

#MSG_SAVE_STATE
保存即时存档

#MSG_SAVE_STATE_END
保存即时存档完成

#MSG_KEY_MAP_NONE
无

#MSG_KEY_MAP_A
A

#MSG_KEY_MAP_B
B

#MSG_KEY_MAP_SL
SELECT

#MSG_KEY_MAP_ST
START

#MSG_KEY_MAP_RT
→

#MSG_KEY_MAP_LF
←

#MSG_KEY_MAP_UP
↑

#MSG_KEY_MAP_DW
↓

#MSG_HOME_MAP_R
R

#MSG_HOME_MAP_L
L

#MSG_HOME_MAP_X
X

#MSG_HOME_MAP_Y
Y

#MSG_HOME_MAP_TOUCH
触摸屏

#MSG_SAVESTATE_EMPTY
当前存档槽没有存档文件!

#MSG_SAVESTATE_EMPTY
当前存档槽已有存档文件,\n
覆盖已有存档吗?\n
按 A 键覆盖\n
按 B 键取消


#MSG_SAVESTATE_DOING
正在写入...

#MSG_SAVESTATE_FAILURE
写入存档失败!\n
按 A 键重试\n
按 B 键取消

#MSG_SAVESTATE_SUCCESS
写入存档成功!

#MSG_SAVESTATE_SLOT_EMPTY
没有游戏截图

#MSG_SAVESTATE_FILE_BAD
存档文件找不到或者损坏!

#MSG_LOADSTATE_DOING
正在加载...

#MSG_LOADSTATE_FAILURE
加载存档失败

#MSG_LOADSTATE_SUCCESS
加载存档成功

#MSG_WARING_DIALOG
按任意键返回

#MSG_TIME_FORMATE
时间

#MSG_SUB_MENU_130
删除当前游戏的所有存档

#MSG_SUB_MENU_131
删除当前游戏的一个存档         %d

#MSG_DELETE_ALL_SAVESTATE_WARING
确定要删除所有存档吗？\n
按 A 键确定 \n
按 B 键取消

#MSG_DELETE_SINGLE_SAVESTATE_WARING
确定要删除存档槽 %d 的存档吗? \n
按 A 键确定 \n
按 B 键取消

#MSG_DELETE_SAVESTATE_NOTHING
没有存档可删除

#MSG_SAVE_SNAPSHOT
正在保存屏幕快照...

#MSG_SAVE_SNAPSHOT_CONPLETE
完成!

#MSG_SAVE_SNAPSHOT_FAILURE
失败!

#MSG_CHANGE_LANGUAGE
正在修改...

#MSG_CHANGE_LANGUAGE_WAITING
请稍候!

#MSG_NO_SLIDE
此目录没有屏幕快照，取消放映

#MSG_PLAYING_SLIDE
正在播放

#MSG_PAUSE_SLIDE
已暂停

#MSG_PLAY_SLIDE1
按键 上  加快播放

#MSG_PLAY_SLIDE2
按键 下  减慢播放

#MSG_PLAY_SLIDE3
按键 左  上一帧

#MSG_PLAY_SLIDE4
按键 右  下一帧

#MSG_PLAY_SLIDE5
按键 A   暂停

#MSG_PLAY_SLIDE6
按键 B   返回菜单

#MSG_LOADING_GMAE
正在装载游戏...

#MSG_EMU_VERSION0
SFC模拟器

#MSG_EMU_VERSION1
版本

#MSG_LOAD_DEFAULT_WARING,
确定将 SFC模拟器恢复为出厂设置吗?

#MSG_DEFAULT_LOADING
正在设置,请稍候...

#MSG_BACK
返回

ENDCHINESESIM


STARTFRENCH

#MSG_MAIN_MENU_0
Vidéo & audio

#MSG_MAIN_MENU_1
Sauvegardes

#MSG_MAIN_MENU_2
Triche

#MSG_MAIN_MENU_3
Outils

#MSG_MAIN_MENU_4
Options

#MSG_MAIN_MENU_5
Quitter

#MSG_SUB_MENU_00
Format d'image      %s

#MSG_SUB_MENU_01
Avance rapide       %s

#MSG_SUB_MENU_02
Omission d'images  %s

#MSG_SUB_MENU_03
Images omises      %d

#MSG_SUB_MENU_04
Son                         %s

#MSG_SUB_MENU_05
Retour

#MSG_SUB_MENU_10
Créer une sauvegarde

#MSG_SUB_MENU_11
Charger la sauvegarde   %d

#MSG_SUB_MENU_12
Sélectionner l'emplacement

#MSG_SUB_MENU_13
Supprimer une/des sauvegardes...

#MSG_SUB_MENU_14
Retour

#MSG_SUB_MENU_20
Page de codes de triche : %d

#MSG_SUB_MENU_21
Charger un fichier de triche

#MSG_SUB_MENU_22
Emplacement de triche

#MSG_SUB_MENU_23
Charger la triche

#MSG_SUB_MENU_24
Retour

#MSG_SUB_MENU_30
Captures d'écran...

#MSG_SUB_MENU_31
Réassigner les contrôles

#MSG_SUB_MENU_32
Gardes les informations pour  %s seconde(s)

#MSG_SUB_MENU_40
Mise en veille automatique     %s

#MSG_SUB_MENU_41
Langue                              %s

#MSG_SUB_MENU_42
Fréquence CPU                  %d

#MGS_SUB_MENU_43
Capacité de la carte

#MSG_SUB_MENU_44
Remettre les paramètres à zéro

#MSG_SUB_MENU_45
Version

#MSG_SUB_MENU_300
Créer une capture d'écran

#MSG_SUB_MENU_301
Parcourir les captures d'écran

#MSG_SUB_MENU_302
Marche arrière             %s

#MSG_SUB_MENU_310
SNES touche A %s

#MSG_SUB_MENU_311
                 B %s

#MSG_SUB_MENU_312
                 Rapid A %s

#MSG_SUB_MENU_313
                 Rapid B %s

#MSG_SUB_MENU_314
Afficher le menu %s

#MSG_SUB_MENU_315
Touche de retour NDS

#MSG_SUB_MENU_60
Jeux joués récemment

#MSG_SUB_MENU_61
Sélectionner un jeu de la carte

#MSG_SUB_MENU_62
Sélectionner un jeu

#MSG_SCREEN_RATIO_0
[0] Écran entier

#MSG_SCREEN_RATIO_1
[1] Couper le haut

#MSG_SCREEN_RATIO_2,
[2] Couper le bas

#MSG_SCREEN_RATIO_3,
[3] Montrer le milieu

#MSG_SCREEN_RATIO_4,
[4] Écran entier

#MSG_FRAMESKIP_0
Manuelle

#MSG_FRAMESKIP_1
Automatique

#MSG_ON_OFF_0
Hors fonction

#MSG_ON_OFF_1
En fonction

#MSG_SOUND_SWITCH_0
Activé

#MSG_SOUND_SWITCH_1
Muet

#MSG_SNAP_FRAME_0
Frame actuelle

#MSG_SNAP_FRAME_1
Dernière Frame

#MSG_EN_DIS_ABLE_0
Désactiver

#MSG_EN_DIS_ABLE_1
Activer

#MSG_NONE_LOAD_GAME
Aucun jeu n'est actuellement chargé

#MSG_CHEAT_MENU_NON_LOAD
Code de triche %d (aucun chargé)

#MSG_CHEAT_MENU_0
Code %d (%s): %%s

#MSG_LOAD_STATE
Charger

#MSG_LOAD_STATE_END
Chargé

#MSG_SAVE_STATE
Sauvegarder

#MSG_SAVE_STATE_END
Terminé!

#MSG_KEY_MAP_NONE
Aucun

#MSG_KEY_MAP_A
A

#MSG_KEY_MAP_B
B

#MSG_KEY_MAP_SL
SELECT

#MSG_KEY_MAP_ST
START

#MSG_KEY_MAP_RT
→

#MSG_KEY_MAP_LF
←

#MSG_KEY_MAP_UP
↑

#MSG_KEY_MAP_DW
↓

#MSG_HOME_MAP_R
R

#MSG_HOME_MAP_L
L

#MSG_HOME_MAP_X
X

#MSG_HOME_MAP_Y
Y

#MSG_HOME_MAP_TOUCH
Écran tactile

#MSG_SAVESTATE_EMPTY
Cet emplacement est vide.

#MSG_SAVESTATE_FULL
Il y a une sauvegarde dans cet emplacement.\n
Voulez-vous l'écraser?\n
[A] Écraser  [B] Annuler

#MSG_SAVESTATE_DOING
Sauvegarde en cours...

#MSG_SAVESTATE_FAILURE
Échec!\n
[A] Réessayer  [B] Annuler

#MSG_SAVESTATE_SUCCESS
Terminé!

#MSG_SAVESTATE_SLOT_EMPTY
Aucune sauvegarde

#MSG_SAVESTATE_FILE_BAD
Le fichier de sauvegarde est introuvable ou corrompu.

#MSG_LOADSTATE_DOING
Chargement en cours...

#MSG_LOADSTATE_FAILURE
Échec!

#MSG_LOADSTATE_SUCCESS
Terminé!

#MSG_WARING_DIALOG
Appuyez sur une touche pour continuer.

#MSG_TIME_FORMATE
Date

#MSG_SUB_MENU_130
Supprimer toutes les sauvegardes

#MSG_SUB_MENU_131
Supprimer l'emplacement %d

#MSG_DELETE_ALL_SAVESTATE_WARING
Supprimer toutes les sauvegardes?\n
[A] Confirmer  [B] Annuler

#MSG_DELETE_SINGLE_SAVESTATE_WARING
Supprimer l'emplacement %d?\n
[A] Confirmer  [B] Annuler

#MSG_DELETE_SAVESTATE_NOTHING
Cet emplacement est déjà vide.

#MSG_SAVE_SNAPSHOT
Capture de l'écran...

#MSG_SAVE_SNAPSHOT_COMPLETE
Terminé!

#MSG_SAVE_SNAPSHOT_FAILURE
Échec!

#MSG_CHANGE_LANGUAGE
Changement de la langue...

#MSG_CHANGE_LANGUAGE_WAITING
Veuillez patienter...

#MSG_NO_SLIDE
Aucune capture d'écran trouvée

#MSG_PLAYING_SLIDE
En cours...

#MSG_PAUSE_SLIDE
Pause...

#MSG_PLAY_SLIDE1
HAUT     Accélérer

#MSG_PLAY_SLIDE2
BAS       Ralentir

#MSG_PLAY_SLIDE3
GAUCHE  Précédente

#MSG_PLAY_SLIDE4
DROITE  Suivante

#MSG_PLAY_SLIDE5
A           Pause

#MSG_PLAY_SLIDE6
B           Retour au menu

#MSG_LOADING_GMAE
Chargement...

#MSG_EMU_VERSION0
Émulateur SNES CATSFC

#MSG_EMU_VERSION1
Version

#MSG_LOAD_DEFAULT_WARING,
Remettre tous les paramètres à zéro?

#MSG_DEFAULT_LOADING
Veuillez patienter...

#MSG_BACK
Retour

ENDFRENCH
